name: Shell Commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo String
        run: echo "Hello Shankar"
      - name: Multi Comm
        run: |
          node -v
          npm -v
          uptime
          hostname
          free -g